name: .NET Core CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore rental-service.sln

      - name: Build
        run: dotnet build rental-service.sln --no-restore --configuration Release

      - name: Test
        run: dotnet test rental-service.sln --no-build --verbosity normal
